### ISSUE TITLE
When I set overflow: auto for flippy-front it shows in the Flippy back in reverse

### ISSUE THREAD

**Issue by forethoughtde** [zwacky/angular-flippy#21]
I set 

``` css
flippy-front{
overflow: auto;
}
```

The flippy-front content is shown in the flippy-back area in reverse along with flippy-back content in Google Chrome web browser.
